### ISSUE TITLE
Remplacement des ids par des UUIDs

### ISSUE THREAD

**Issue by ftoumHub** [ftoumHub/lean-app-engineering#7]
Dans l'objet Issue, l'identifiant est représenter par un objet de type Long.
Remplacer cette objet par un objet de type UUID et généré un identifiant avant de persister une issue en base.

**Comment by ftoumHub** [comment]
Articles à lire :
https://mareks-082.medium.com/auto-increment-keys-vs-uuid-a74d81f7476a

https://www.clever-cloud.com/fr/blog/engineering-fr/2015/05/20/why-auto-increment-is-a-terrible-idea/

**Comment by olivierF-Git** [comment]
Est ce que ce genre d'ID est celui attendu ? 
de52c791-bb10-415d-8bd6-aecc73db96a8
Puisqu'effectivement c'est un UUID, j'arrive à l'insérer, le supprimer et l'auto-incrémenter.
Cependant, ce n'est pas spécialement esthétique.
